services:

    flux_se.sylius_eu_vat_plugin.form.extension.vat_number:
        class: FluxSE\SyliusEUVatPlugin\Form\Extension\VATNumberTypeExtension
        tags:
            - { name: form.type_extension }

    flux_se.sylius_eu_vat_plugin.form.extension.channel:
        class: FluxSE\SyliusEUVatPlugin\Form\Extension\ChannelTypeExtension
        tags:
            - { name: form.type_extension }
