services:

    flux_se.sylius_eu_vat.shop.twig.component.checkout.address.form:
        decorates: sylius_shop.twig.component.checkout.address.form
        class: FluxSE\SyliusEUVatPlugin\Twig\Component\Checkout\Address\FormComponent
        arguments:
            - '@sylius.repository.order'
            - '@form.factory'
            - '%sylius.model.order.class%'
            - 'Sylius\Bundle\ShopBundle\Form\Type\Checkout\AddressType'
            - '@sylius.context.customer'
            - '@sylius.repository.shop_user'
            - '@sylius.repository.address'
