services:
    prometee.sylius_viesclient_plugin.applicator.order_european_vatnumber_applicator:
        class: Prometee\SyliusVIESClientPlugin\Applicator\OrderEuropeanVATNumberApplicator
        arguments:
            $viesHelper: '@Prometee\VIESClient\Helper\ViesHelper'
