services:
    flux_se.sylius_eu_vat_plugin.fixture.factory.european_channel_example:
        public: true
        class: FluxSE\SyliusEUVatPlugin\Fixture\Factory\EuropeanChannelExampleFactory
        arguments:
            $channelRepository: '@sylius.repository.channel'
            $countryRepository: '@sylius.repository.country'
            $zoneRepository: '@sylius.repository.zone'
    
    flux_se.sylius_eu_vat_plugin.fixture.european_channel:
        public: true
        class: FluxSE\SyliusEUVatPlugin\Fixture\EuropeanChannelFixture
        arguments:
            $objectManager: '@sylius.manager.channel'
            $exampleFactory: '@flux_se.sylius_eu_vat_plugin.fixture.factory.european_channel_example'
        tags:
            - { name: sylius_fixtures.fixture }

    flux_se.sylius_eu_vat_plugin.fixture.factory.address_example:
        public: true
        class: FluxSE\SyliusEUVatPlugin\Fixture\Factory\AddressExampleFactory
        arguments:
            $addressFactory: '@sylius.factory.address'
            $countryRepository: '@sylius.repository.country'
            $customerRepository: '@sylius.repository.customer'
            $viesHelper: '@Prometee\VIESClient\Helper\ViesHelper'

    flux_se.sylius_eu_vat_plugin.fixture.address:
        public: true
        class: FluxSE\SyliusEUVatPlugin\Fixture\AddressFixture
        arguments:
            $objectManager: '@sylius.manager.address'
            $exampleFactory: '@flux_se.sylius_eu_vat_plugin.fixture.factory.address_example'
        tags:
            - { name: sylius_fixtures.fixture }
