sylius_fixtures:
    suites:

        european_vat_zones:

            listeners:
                logger: ~

            fixtures:

                geographical:
                    options:
                        zones:
                            EU:
                                name: "European Union"
                                countries:
                                    - "AT"
                                    - "BE"
                                    - "BG"
                                    - "HR"
                                    - "CY"
                                    - "CZ"
                                    - "DK"
                                    - "EE"
                                    - "FI"
                                    - "FR"
                                    - "DE"
                                    - "GR"
                                    - "HU"
                                    - "IE"
                                    - "IT"
                                    - "LV"
                                    - "LT"
                                    - "LU"
                                    - "MT"
                                    - "NL"
                                    - "PL"
                                    - "PT"
                                    - "RO"
                                    - "SK"
                                    - "SI"
                                    - "ES"
                                    - "SE"
                                    # This are french overseas departments
                                    # Disable those not real countries if you are managing French VAT
                                    #- "BL"
                                    #- "GF"
                                    #- "GP"
                                    #- "MF"
                                    #- "MQ"
                                    #- "NC"
                                    #- "PF"
                                    #- "PM"
                                    #- "RE"
                                    #- "TF"
                                    #- "YT"
                                    #- "WF"
                            REST_OTW:
                                name: "Rest of the world"
                                countries:
                                    - "AD"
                                    - "AE"
                                    - "AF"
                                    - "AG"
                                    - "AI"
                                    - "AL"
                                    - "AM"
                                    - "AO"
                                    - "AQ"
                                    - "AR"
                                    - "AS"
                                    - "AU"
                                    - "AW"
                                    - "AX"
                                    - "AZ"
                                    - "BA"
                                    - "BB"
                                    - "BD"
                                    - "BF"
                                    - "BH"
                                    - "BI"
                                    - "BJ"
                                    - "BM"
                                    - "BN"
                                    - "BO"
                                    - "BQ"
                                    - "BR"
                                    - "BS"
                                    - "BT"
                                    - "BV"
                                    - "BW"
                                    - "BY"
                                    - "BZ"
                                    - "CA"
                                    - "CC"
                                    - "CD"
                                    - "CF"
                                    - "CG"
                                    - "CH"
                                    - "CI"
                                    - "CK"
                                    - "CL"
                                    - "CM"
                                    - "CN"
                                    - "CO"
                                    - "CR"
                                    - "CU"
                                    - "CV"
                                    - "CW"
                                    - "CX"
                                    - "DJ"
                                    - "DM"
                                    - "DO"
                                    - "DZ"
                                    - "EC"
                                    - "EG"
                                    - "EH"
                                    - "ER"
                                    - "ET"
                                    - "FJ"
                                    - "FK"
                                    - "FM"
                                    - "FO"
                                    - "GA"
                                    - "GB"
                                    - "GD"
                                    - "GE"
                                    - "GG"
                                    - "GH"
                                    - "GI"
                                    - "GL"
                                    - "GM"
                                    - "GN"
                                    - "GQ"
                                    - "GS"
                                    - "GT"
                                    - "GU"
                                    - "GW"
                                    - "GY"
                                    - "HK"
                                    - "HM"
                                    - "HN"
                                    - "HT"
                                    - "ID"
                                    - "IL"
                                    - "IM"
                                    - "IN"
                                    - "IO"
                                    - "IQ"
                                    - "IR"
                                    - "IS"
                                    - "JE"
                                    - "JM"
                                    - "JO"
                                    - "JP"
                                    - "KE"
                                    - "KG"
                                    - "KH"
                                    - "KI"
                                    - "KM"
                                    - "KN"
                                    - "KP"
                                    - "KR"
                                    - "KW"
                                    - "KY"
                                    - "KZ"
                                    - "LA"
                                    - "LB"
                                    - "LC"
                                    - "LI"
                                    - "LK"
                                    - "LR"
                                    - "LS"
                                    - "LY"
                                    - "MA"
                                    - "MC"
                                    - "MD"
                                    - "ME"
                                    - "MG"
                                    - "MH"
                                    - "MK"
                                    - "ML"
                                    - "MM"
                                    - "MN"
                                    - "MO"
                                    - "MP"
                                    - "MR"
                                    - "MS"
                                    - "MU"
                                    - "MV"
                                    - "MW"
                                    - "MX"
                                    - "MY"
                                    - "MZ"
                                    - "NA"
                                    - "NE"
                                    - "NF"
                                    - "NG"
                                    - "NI"
                                    - "NO"
                                    - "NP"
                                    - "NR"
                                    - "NU"
                                    - "NZ"
                                    - "OM"
                                    - "PA"
                                    - "PE"
                                    - "PG"
                                    - "PH"
                                    - "PK"
                                    - "PN"
                                    - "PR"
                                    - "PS"
                                    - "PW"
                                    - "PY"
                                    - "QA"
                                    - "RS"
                                    - "RU"
                                    - "RW"
                                    - "SA"
                                    - "SB"
                                    - "SC"
                                    - "SD"
                                    - "SG"
                                    - "SH"
                                    - "SJ"
                                    - "SL"
                                    - "SM"
                                    - "SN"
                                    - "SO"
                                    - "SR"
                                    - "SS"
                                    - "ST"
                                    - "SV"
                                    - "SX"
                                    - "SY"
                                    - "SZ"
                                    - "TC"
                                    - "TD"
                                    - "TG"
                                    - "TH"
                                    - "TJ"
                                    - "TK"
                                    - "TL"
                                    - "TM"
                                    - "TN"
                                    - "TO"
                                    - "TR"
                                    - "TT"
                                    - "TV"
                                    - "TW"
                                    - "TZ"
                                    - "UA"
                                    - "UG"
                                    - "UM"
                                    - "US"
                                    - "UY"
                                    - "UZ"
                                    - "VA"
                                    - "VC"
                                    - "VE"
                                    - "VG"
                                    - "VI"
                                    - "VN"
                                    - "VU"
                                    - "WS"
                                    - "YE"
                                    - "ZA"
                                    - "ZM"
                                    - "ZW"

# Example of european_channel fixtures 
#        european_channel:
#            listeners:
#                logger: ~
#
#            fixtures:
#                vies_plugin_european_channel:
#                    options:
#                        custom:
#                            default:
#                                channel: "default_channel_code" # put an existing Channel code
#                                base_country: "FR" # Existing Country code
#                                european_zone: "EU" # existing Zone code
