sylius_twig_hooks:
    hooks:
        'sylius_shop.checkout.address.content.form.addresses.billing_address':
            address_book:
                props:
                    template: '@FluxSESyliusEUVatPlugin/shop/checkout/address/content/form/addresses/address_book.html.twig'
        'sylius_shop.checkout.address.content.form.addresses.shipping_address':
            address_book:
                props:
                    template: '@FluxSESyliusEUVatPlugin/shop/checkout/address/content/form/addresses/address_book.html.twig'
